apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-world-k8s-deployment
  labels:
    k8s-app: hello-world-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: hello-world-k8s-deployment
  template:
    metadata:
      labels:
        k8s-app: hello-world-k8s-deployment
    spec:
      imagePullSecrets:
      - name: __DOCKER_REGISTRY__-regcred
      containers:
      - image: __DOCKER_REGISTRY__/__DOCKER_IMAGE__:__APP_VERSION__
        name: hello-world-k8s
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-k8s-svc
  labels:
    k8s-app: hello-world-k8s-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: hello-world-k8s-deployment
  type: LoadBalancer

